[phases.setup]
nixPkgs = ['...', 'dotnet-sdk_8']

[phases.build]
cmds = [
  'cd backend/ProjectManagerAPI',
  'dotnet restore',
  'dotnet publish -c Release -o /app/publish'
]

[start]
cmd = 'cd /app/publish && dotnet ProjectManagerAPI.dll --urls="http://0.0.0.0:$PORT"'